apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::888007655814:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NO5S13PG66J8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::888007655814:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-18T02:05:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1574"
  uid: 73c97c14-5b5f-4b3c-949a-565d462afc5a
